name: inventory
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.0.1
  kiwi: ^0.2.0
  json_annotation: ^2.2.0
  http: ^0.12.0
  url_launcher: ^5.0.2
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  meta: ^1.1.6
  equatable: ^0.2.0
  shared_preferences: ^0.5.6+2
  location: "^2.0.0"
  image_picker: "^0.5.0+9"
  qr_flutter: ^3.1.0
  flutter_barcode_scanner: ^0.1.7
  flutter_slidable: ^0.5.4
  flutter_launcher_icons: "^0.7.4"
  google_maps_flutter: ^0.5.25+2
  google_fonts: ^0.3.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0
  kiwi_generator: ^0.4.0
  json_serializable: ^2.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/inventory_s.png"

flutter:

  assets:
    - assets/cfg/

  uses-material-design: true

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSansRegular.ttf
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900
    - family: RobotoCondensed
      fonts:
        - asset: assets/fonts/RobotoCondensed-Regular.ttf
        - asset: assets/fonts/RobotoCondensed-Italic.ttf
          style: italic
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
          weight: 700

